# Change these first
owner: AurAchieve # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: App Server/API
    url: https://api.aurachieve.com
  - name: Website
    url: https://aurachieve.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.aurachieve.com
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/217299217?s=200&v=4
  name: AurAchieve
  introTitle: "AurAchieve"
  introMessage: "Check for the status of **AurAchieve** services here."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
