# Change these first
owner: AurAchieve # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: App Server/API
    url: https://api.aurachieve.com
    type: globalping
  - name: AuraPages
    url: https://aurapage.me
    type: globalping
    location: frankfurt
  - name: Website
    url: https://aurachieve.com
    type: globalping

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.aurachieve.com
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/217299217?s=200&v=4
  name: AurAchieve
  introTitle: "AurAchieve Status"
  introMessage: "Check for the status of **AurAchieve** services here. If everything seems okay here and you're still facing issues, shoot a email to [support@aurachieve.com](mailto:support@aurachieve.com)"
  theme: light
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
  customHeadHtml: |
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <script>
    document.addEventListener('DOMContentLoaded', function() {
      var header = document.querySelector('header');
      if (!header) return;
      var hasDown = document.querySelectorAll('.tag.down, .tag.open').length > 0;
      var hasDegraded = document.querySelectorAll('.tag.degraded').length > 0;
      var statusClass = hasDown ? 'down' : (hasDegraded ? 'degraded' : 'operational');
      var statusText = hasDown ? 'Some systems are experiencing issues' : (hasDegraded ? 'Some systems are degraded' : 'All systems operational');
      var wrapper = document.createElement('div');
      wrapper.style.cssText = 'display:flex;justify-content:center;margin-bottom:1.5rem;';
      wrapper.innerHTML = '<span class="status-badge ' + statusClass + '"><span class="status-dot"><span class="status-dot-ping"></span><span class="status-dot-core"></span></span>' + statusText + '</span>';
      header.insertBefore(wrapper, header.firstChild);
      var footer = document.querySelector('footer');
      if (footer) {
        var contactLine = document.createElement('p');
        contactLine.className = 'footer-contact';
        contactLine.innerHTML = 'Contact us at <a href="mailto:hello@aurachieve.com">hello@aurachieve.com</a> to report an issue.';
        footer.appendChild(contactLine);
      }
    });
    </script>
  css: |
    /* Better Stack-inspired theme */
    :root {
      --body-background-color: #f9fafb;
      --body-text-color: #111827;
      --card-background-color: #ffffff;
      --nav-background-color: #ffffff;
      --nav-border-bottom-color: #e5e7eb;
      --nav-current-border-bottom-color: #22c55e;
      --card-border-color: #e5e7eb;
      --down-border-left-color: #ef4444;
      --down-background-color: #fef2f2;
      --degraded-border-left-color: #f59e0b;
      --up-border-left-color: #22c55e;
      --up-color-color: #111827;
      --down-color-color: #111827;
      --degraded-color-color: #111827;
      --tag-color: inherit;
      --tag-up-background-color: #dcfce7;
      --tag-down-background-color: #fee2e2;
      --tag-degraded-background-color: #fef3c7;
      --change-background-color: #fef3c7;
      --graph-opacity: 1;
      --graph-filter: none;
    }
    body {
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    }
    nav {
      box-shadow: 0 1px 3px rgba(0,0,0,0.06);
      margin-bottom: 2.5rem;
      padding: 0;
    }
    nav .container {
      height: 64px;
    }
    .logo img {
      border-radius: 50% !important;
      height: 2rem !important;
    }
    .logo div {
      display: none !important;
    }
    nav ul a {
      padding: 0.75rem 1rem;
      font-size: 0.875rem;
      font-weight: 500;
    }
    header {
      text-align: center;
      padding: 3rem 0 2.5rem;
      margin-bottom: 0;
    }
    header h1 {
      font-size: 2.25rem;
      font-weight: 700;
      letter-spacing: -0.025em;
      color: #111827;
    }
    header p.lead {
      color: #6b7280;
      font-size: 1rem;
      max-width: 560px;
      margin: 0.75rem auto 0;
    }
    article {
      border-radius: 0.5rem;
      box-shadow: 0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04);
      padding: 1rem 1.25rem;
    }
    article h4 {
      font-weight: 500;
      font-size: 0.9375rem;
    }
    .tag {
      border-radius: 9999px;
      font-size: 0.75rem;
      font-weight: 500;
      padding: 0.25rem 0.625rem;
    }
    .tag.up, .tag.closed {
      color: #15803d !important;
    }
    .tag.down, .tag.open {
      color: #b91c1c !important;
    }
    .tag.degraded {
      color: #b45309 !important;
    }
    h2 {
      font-weight: 600;
      font-size: 1.125rem;
    }
    h3 {
      opacity: 1;
      color: #9ca3af;
      font-size: 0.75rem;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      font-weight: 500;
    }
    footer {
      color: #9ca3af;
      font-size: 0.875rem;
      margin-top: 4rem;
    }
    .footer-contact {
      margin-top: 0.5rem;
      color: #6b7280;
    }
    .footer-contact a {
      color: #22c55e;
      text-decoration: none;
      font-weight: 500;
    }
    .footer-contact a:hover {
      text-decoration: underline;
    }
    @keyframes upptime-ping {
      75%, 100% { transform: scale(2.5); opacity: 0; }
    }
    @keyframes upptime-pulse {
      0%, 100% { opacity: 1; }
      50% { opacity: 0.6; }
    }
    .status-badge {
      display: inline-flex;
      align-items: center;
      gap: 0.625rem;
      border-radius: 9999px;
      padding: 0.5rem 1.25rem;
      font-size: 0.875rem;
      font-weight: 500;
    }
    .status-badge.operational {
      background: #dcfce7;
      color: #15803d;
      border: 1px solid #bbf7d0;
    }
    .status-badge.degraded {
      background: #fef3c7;
      color: #b45309;
      border: 1px solid #fde68a;
    }
    .status-badge.down {
      background: #fee2e2;
      color: #dc2626;
      border: 1px solid #fecaca;
    }
    .status-dot {
      position: relative;
      width: 10px;
      height: 10px;
      flex-shrink: 0;
      display: inline-block;
    }
    .status-dot-ping {
      position: absolute;
      inset: 0;
      border-radius: 50%;
      animation: upptime-ping 1.5s cubic-bezier(0, 0, 0.2, 1) infinite;
      opacity: 0.75;
    }
    .status-dot-core {
      position: absolute;
      inset: 0;
      border-radius: 50%;
      animation: upptime-pulse 2s ease-in-out infinite;
    }
    .operational .status-dot-ping,
    .operational .status-dot-core { background: #22c55e; }
    .degraded .status-dot-ping,
    .degraded .status-dot-core { background: #f59e0b; }
    .down .status-dot-ping,
    .down .status-dot-core { background: #ef4444; }
  workflowSchedule:
    uptime: "*/2 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
